#!/bin/bash

# Supervised Contrastive Pre-Training
#python main_supcon.py --dataset 'Image_2022_Volumetric_Contrastive' --discrete_level 10 --method 'SupCon'

#python main_supcon.py --dataset 'Image_2022_Volumetric_Contrastive' --discrete_level 50 --method 'SupCon'

#python main_supcon.py --dataset 'Image_2022_Volumetric_Contrastive' --discrete_level 100 --method 'SupCon'

#python main_supcon.py --dataset 'Image_2022_Volumetric_Contrastive' --discrete_level 150 --method 'SupCon'

#python main_supcon.py --dataset 'Image_2022_Volumetric_Contrastive' --discrete_level 0 --method 'SimCLR'

# SimCLR

python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 1 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SimCLR_Seismic_resnet18_lr_0_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 2 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SimCLR_Seismic_resnet18_lr_0_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 3 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SimCLR_Seismic_resnet18_lr_0_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'

# 10


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 1 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_10_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 2 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_10_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 3 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_10_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'

# 50


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 1 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_50_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'



python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 2 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_50_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'



python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 3 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_50_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'

# 100


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 1 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_100_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 2 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_100_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 3 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_100_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'

# 150


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 1 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_150_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 2 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_150_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'


python main_seismic_semantic.py --dataset 'Image_2022_Volumetric_Contrastive' --test_split 3 --epochs 50 --batch_size 64 --ckpt '/home/kiran/Desktop/Dev/Image_2022_Volumetric_Contrastive/SupContrast/save/SupCon/Seismic_models/SupCon_Seismic_resnet18_lr_150_0.001_decay_0.0001_bsz_64_temp_0.07_trial_0/last.pth'
